"""
Markdown 输出格式化器
生成 Markdown 格式的测试用例报告
"""

import json
from datetime import datetime
from typing import Dict, List, Any


class MarkdownFormatter:
    """Markdown 格式化器"""

    def __init__(self, module_name: str = "TestModule", base_url: str = ""):
        self.module_name = module_name
        self.base_url = base_url
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def format(self, testcases: List[Dict], api_info: Dict = None) -> str:
        """
        格式化测试用例为 Markdown

        Args:
            testcases: 测试用例列表
            api_info: API 信息

        Returns:
            Markdown 格式的测试用例报告
        """
        md = self._header(api_info)

        # 按类型分组
        api_cases = [tc for tc in testcases if tc.get('用例编号', '').startswith('API_')]
        func_cases = [tc for tc in testcases if tc.get('功能ID', '').startswith('FUNC_')]

        if api_cases:
            md += self._format_api_cases(api_cases)

        if func_cases:
            md += self._format_functional_cases(func_cases)

        md += self._footer()

        return md

    def _header(self, api_info: Dict = None) -> str:
        """生成文档头部"""
        md = f"""# 测试用例报告

## 基本信息

| 字段 | 值 |
|------|-----|
| **模块名称** | {self.module_name} |
| **Base URL** | {self.base_url} |
| **生成时间** | {self.timestamp} |
| **用例总数** | 待统计 |

"""
        if api_info:
            md += f"""### API 信息

- **名称**: {api_info.get('name', 'Unknown')}
- **描述**: {api_info.get('description', '无')}
- **接口数量**: {api_info.get('api_count', 0)}

"""
        return md

    def _format_api_cases(self, cases: List[Dict]) -> str:
        """格式化接口测试用例"""
        md = f"""## 接口测试用例

### 用例汇总

| 用例编号 | 用例标题 | 优先级 | 请求方法 | 预期状态 | 是否假设 | 断言来源 |
|----------|----------|--------|----------|----------|----------|----------|
"""
        for tc in cases:
            md += (
                f"| {tc.get('用例编号', '')} | {tc.get('用例标题', '')} | "
                f"{tc.get('模块/优先级', '').split('/')[-1]} | {tc.get('请求类型', '')} | "
                f"{tc.get('预期响应状态', '')} | {tc.get('是否为假设', '否')} | "
                f"{tc.get('断言来源', '')} |\n"
            )

        md += """
### 详细用例

"""
        for tc in cases:
            md += f"""#### {tc.get('用例编号')}: {tc.get('用例标题')}

| 字段 | 值 |
|------|-----|
| 模块/优先级 | {tc.get('模块/优先级', '')} |
| 接口名称 | {tc.get('接口名称', '')} |
| 前置条件 | {tc.get('前置条件', '')} |
| 请求URL | `{tc.get('请求URL', '')}` |
| 请求类型 | {tc.get('请求类型', '')} |
| 请求头 | {tc.get('请求头', '').replace(chr(10), '<br>')} |
| 请求参数类型 | {tc.get('请求参数类型', '')} |
| 请求数据 | `{tc.get('请求数据', '')[:200]}` |
| 预期响应状态 | {tc.get('预期响应状态', '')} |
| 预期响应信息 | `{tc.get('预期响应信息', '')}` |
| 断言来源 | {tc.get('断言来源', '')} |
| 是否为假设 | {tc.get('是否为假设', '否')} |
| 实际响应信息 | {tc.get('实际响应信息', '待执行')} |
| 是否通过 | {tc.get('是否通过', '待执行')} |
| 测试类型 | {tc.get('测试类型', '接口')} |
| 备注 | {tc.get('备注', '')} |

---

"""

        return md

    def _format_functional_cases(self, cases: List[Dict]) -> str:
        """格式化功能测试用例"""
        md = f"""## 功能测试用例

### 用例汇总

| 用例ID | 用例标题 | 优先级 | 功能模块 | 预置条件 |
|--------|----------|--------|----------|----------|
"""
        for tc in cases:
            md += f"| {tc.get('功能ID', '')} | {tc.get('用例标题', '')} | {tc.get('优先级', '')} | {tc.get('功能模块', '')} | {tc.get('预置条件', '')} |\n"

        md += """
### 详细用例

"""
        for tc in cases:
            md += f"""#### {tc.get('功能ID')}: {tc.get('用例标题')}

| 字段 | 值 |
|------|-----|
| 功能模块 | {tc.get('功能模块', '')} |
| 优先级 | {tc.get('优先级', '')} |
| 预置条件 | {tc.get('预置条件', '')} |
| 测试数据 | {tc.get('测试数据', '')} |
| 执行步骤 | {tc.get('执行步骤', '').replace(chr(10), '<br>')} |
| 预期结果 | {tc.get('预期结果', '')} |
| 断言来源 | {tc.get('断言来源', '')} |
| 是否为假设 | {tc.get('是否为假设', '是')} |
| 测试结果 | {tc.get('测试结果', '待执行')} |
| 测试版本号 | {tc.get('测试版本号', '')} |
| 测试人员 | {tc.get('测试人员', '')} |
| 备注 | {tc.get('备注', '')} |
| 测试类型 | {tc.get('测试类型', '功能')} |

---

"""

        return md

    def _footer(self) -> str:
        """生成文档尾部"""
        return f"""

## 测试统计

| 统计项 | 数量 |
|--------|------|
| 生成时间 | {self.timestamp} |
| 模块 | {self.module_name} |

> **注意**: 本测试用例由自动化工具生成，请根据实际情况调整测试数据和预期结果。

---

*Generated by TestCase Generator*
"""

    def save(self, content: str, filepath: str):
        """保存 Markdown 文件"""
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return filepath


# 便捷函数
def format_markdown(testcases: List[Dict], module_name: str, base_url: str = "", api_info: Dict = None) -> str:
    """格式化测试用例为 Markdown"""
    return MarkdownFormatter(module_name, base_url).format(testcases, api_info)
